# Numpy ( Ferrari for Mathematical Computing)
### Official Documentation : https://numpy.org/doc/
####  NumPy (Numerical Python) is an open source Python library that’s widely used in science and engineering. The NumPy library contains multidimensional array data structures, like n dimension arrays, large library of functions, and efficient mathematical operations.



In [ ]:
## To import numpy after pip installing call
import numpy as np

eg = np.array([[1,2,3],
                [4,5,6]])
eg.shape

(2, 3)

In [51]:
my_var = np.array([10,30,20.5, 15,30,40.0])

In [53]:
my_var

array([10. , 30. , 20.5, 15. , 30. , 40. ])

In [4]:
print(eg)

[[1 2 3]
 [4 5 6]]


In [5]:
type(eg)

numpy.ndarray

# Why use Numpy?
## 1. Lists are slow; Numpy is super fast [ Because numpy uses fixed types, optimized operations vs, Python lists are general purpose "hetrogeneous" containers] 
## 2. Numpy uses contiguous memory vs, List are scattered around (pointers + Linked list)
## 3. operations by Element ( Lists do not allow, Num py allows)

# Applications of Numpy
## Mathematical operations ( Scipy is more powerful) https://pypi.org/project/scipy/ SciPy is a collection of mathematical algorithms and convenience functions built on NumPy .
##                          It adds significant power to Python by providing the user with high-level commands and classes for manipulating and visualizing data.
##                          Organised into subpackages like : cluster, constants , differentiate, fft, fftpack, integrate, io, linalg, ndimage, odr, optimize, signal, sparse, spatial, stats
##
## Plotting (Matplotlib)
## Backend (Pandas, Connect4, digital photography)




In [58]:
list1 = [[1,2,3],[4,5,6],[7,8,9]]
list2 = [[0,1,2],[3,4,5],[6,7,8]]

##  this will give error
# list3 = list1*list2
print(list1)
print(list1)



[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [56]:
list1 = [1,2,3]
list2 = [4,5,6]

list4 = list1 * 3
list4

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [ ]:
l1 =np.array(list1)
l2 = np.array(list2)
print ( f" addition : {l1+l2}") # element addition
print ( f" multiplication : {l1 * l2}") # element multipliction

 addition : [5 7 9]
 multiplication : [ 4 10 18]


In [59]:
ex_list = [ [2,3,4],[0,1,2]]
len(ex_list)

2

In [60]:
len(ex_list[0])

3

In [22]:
import time

start_time = time.perf_counter()

rows_a = len(list1)
cols_a = len(list1[0])
rows_b = len(list2)
cols_b = len(list2[0])

if cols_a != rows_b:
    print ("Invalid matrix dimensons")
else:
    list3 = [[0 for _ in range(cols_b)] for _ in range(rows_a)]
    for row in range(rows_a):
        for col in range(cols_b):
            sum_product =0
            for element in range(cols_a):
                sum_product += list1[row][element] * list2[element][col]
            list3[row][col] =sum_product
    print (list3)

tot_run_time = time.perf_counter() - start_time
print(f"Total elapsed time is : {tot_run_time}")   

[[24, 30, 36], [51, 66, 81], [78, 102, 126]]
Total elapsed time is : 0.000594600016484037


In [63]:
rows_a = len(list1)
cols_a = len(list1[0])
rows_b = len(list2)
cols_b = len(list2[0]) 

list3 = [[0 for _ in range(cols_b)] for _ in range(rows_a)]
for row in range(rows_a):
    for col in range(cols_b):
        sum_product =0
        for element in range(cols_a):
            sum_product += list1[row][element] * list2[element][col]
            list3[row][col] =sum_product
print (list3)

[[24, 30, 36], [51, 66, 81], [78, 102, 126]]


In [ ]:
## using  numpy
list1 =np.array([[1,2,3],[4,5,6],[7,8,9]])
list2 =np.array([[0,1,2],[3,4,5],[6,7,8]])

start_time = time.perf_counter()

list3 = list1 @ list2 # use @ operator for matrix multiplication * operator will do scaler multiplication
print (list3)
tot_run_time = time.perf_counter() - start_time
print(f"Total elapsed time is : {tot_run_time}")   

[[ 24  30  36]
 [ 51  66  81]
 [ 78 102 126]]
Total elapsed time is : 0.0005223000189289451


In [27]:
### Array Attributes
## Number of dimensions of array is contained in ndim attribute

print(f"Dimension of Array list3 is : {list3.ndim}")

## shape of array is tuple of non-negative integers for each dimension
print(f"Shape of Array list3 is : {list3.shape}")

## Total number of elements in array is contained in size attribute

print(f"Size of Array list3 is : {list3.size}")

## dype attributes describes the data types
print(f"Data Type of Array list3 is : {list3.dtype}")

Dimension of Array list3 is : 2
Shape of Array list3 is : (3, 3)
Size of Array list3 is : 9
Data Type of Array list3 is : int64


In [ ]:
# Access specific element of array is [r,c]
list3[2,2]

# you can use slicing intervals with positive , negative mix like list

np.int64(126)

# Creating Basic arrays

## np.zeros() - creates  array with all elements o
## np.ones() - creates array with all elements 1
## np.empty() - creates an array whose intial content is random (memory state)
## np.arrange() - creates  with range of elements
## np.linspace() - creates an array with values that are linearly spaced interval



In [35]:
eg_1d = np.zeros(12)
print(eg_1d)
eg = np.zeros((3,4,2))
eg

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [65]:
eg = np.zeros((3,3))
eg

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [36]:
eg_1d = np.ones(12)
print(eg_1d)
eg = np.ones((3,4,2))
eg

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [72]:
eg_1d = np.ones((12,2,3,4,5))
eg_1d

array([[[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]],



       [[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1

In [73]:
list6 = [[1,2,3],[1,4],[3]]
list6

[[1, 2, 3], [1, 4], [3]]

In [37]:
eg_1d = np.full(12,10)
print(eg_1d)
eg = np.full((3,4,2),999)
eg

[10 10 10 10 10 10 10 10 10 10 10 10]


array([[[999, 999],
        [999, 999],
        [999, 999],
        [999, 999]],

       [[999, 999],
        [999, 999],
        [999, 999],
        [999, 999]],

       [[999, 999],
        [999, 999],
        [999, 999],
        [999, 999]]])

In [ ]:
eg_random =np.random.rand(4,2)
eg_random

In [40]:
eg_random =np.random.randint(7,size = (4,2))
eg_random

array([[2, 4],
       [5, 2],
       [0, 4],
       [4, 6]], dtype=int32)

In [41]:
eg_random =np.random.randint(-7,7,size = (4,2))
eg_random

array([[-1, -5],
       [-7, -1],
       [ 1, -6],
       [ 4, -2]], dtype=int32)

In [42]:
list3.max()

np.int64(126)

In [43]:
list3.sum()

np.int64(594)

In [44]:
## Be careful when copying Arrays!
a=np.array([1,2,3])
b=a
b[0] =11
print(b)
print(a)

[11  2  3]
[11  2  3]


In [45]:
## Be careful when copying Arrays!
a=np.array([1,2,3])
b=a.copy()
b[0] =11
print(b)
print(a)

[11  2  3]
[1 2 3]


In [48]:
## Element wise operations
## Matrix operations
print(a+10)
print(np.sin(a))
print(np.cos(a))
print(a**2)

[11 12 13]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[1 4 9]


In [49]:
# Unique items and Counts
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]
